# version: "3.9"
# services:
#   go:
#     build: .
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/app
#   mysql:
#     image: mysql:8.0.29
#     platform: linux/amd64
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#       MYSQL_DATABASE: first
#     volumes:
#       - db-vol:/var/lib/mysql
#     ports:
#       - "3306:3306"
# volumes:
#   db-vol:


version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    platform: linux/amd64 
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3305:3306

  # # phpMyAdmin
  # phpmyadmin:
  #   container_name: test_phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #   - PMA_ARBITRARY=1
  #   - PMA_HOSTS=mysql_host
  #   - PMA_USER=root
  #   - PMA_PASSWORD=root
  #   ports:
  #   - 8080:80
